## Домашнее задание «Библиотека Pandas»

### Задание 1
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [4]:
import pandas as pd
data = pd.read_csv('ratings.csv')

data_rating = data[ data['rating'] == 5 ]
data_rating['movieId'].value_counts().head(1).reset_index()

   index  movieId
0    318      153

### Задача 2
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [13]:
data = pd.read_csv('power.csv')
countries_filter = data[ (data['country']=='Latvia') | (data['country']=='Lithuania') | (data['country']=='Estonia')]
new_data = countries_filter.sort_values(by=['year', 'category' ], ascending=[True, True])

a = new_data[ (new_data.year >= 2005) & (new_data.year <= 2010) & 
            ((new_data.category == 4) | (new_data.category == 12) | (new_data.category == 21)) & 
            (new_data.quantity >= 0)]
sum_ = round (countries_filter.quantity.sum())
print('Table. Суммарное потребление товаров странами Прибалтики (Латвия, Литва и Эстония) за период с 2005 по 2010 года. ')
print('Страны Прибалтики потребляют суммарно =', sum_)
a.groupby(['year','category'])['quantity'].sum().reset_index()

Table. Суммарное потребление товаров странами Прибалтики (Латвия, Литва и Эстония) за период с 2005 по 2010 года.
Страны Прибалтики потребляют суммарно = 117993409.0

    year  category  quantity
0   2005         4      22.0
1   2005        12      18.0
2   2005        21   37124.0
3   2006         4      12.0
4   2006        12      18.0
5   2006        21   38700.0
6   2007         4       0.0
7   2007        12    2454.0
8   2007        21   39012.0
9   2008         4      12.0
10  2008        12    2029.0
11  2008        21   39536.0
12  2009         4       0.0
13  2009        12     862.0
14  2009        21   41920.0
15  2010         4       0.0
16  2010        12     945.0
17  2010        21   37916.0

### Задание 3
Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.
https://fortrader.org/quotes

In [15]:
pd.read_html('https://www.finam.ru/quotes/indices')[0]

,Unnamed: 0,Инструмент,Посл. сделка,% Изм. цены,Открытие,Макс.,Мин.,Закрытие,"Объем, шт.",Время обн.
0,NaN,AMMEKS*,2336.19,-1.1%,2365.000,2365.000,2328.130,2362.290,NaN,19.12 00:10
1,NaN,ASX200 (Австралия)*,6675.5,-1.2%,6756.700,6765.700,6675.500,6756.700,NaN,18.12 08:10
2,NaN,Bovespa (Бразилия),118023.67,-0.32%,118395.230,119370.480,117638.240,118400.570,NaN,19.12 00:20
3,NaN,BSE Sensex (Индия),46960.69,0.15%,47026.020,47026.020,46630.310,46890.340,NaN,18.12 13:29
4,NaN,CAC 40,5527.84,-0.39%,5533.780,5581.960,5519.170,5549.460,NaN,18.12 20:00
5,NaN,CSI200 (Китай),5269.986,-0.05%,5277.341,5289.536,5246.011,5272.637,4 294 967 295,18.12 10:00
6,NaN,CSI300 (Китай),4999.968,-0.35%,5014.321,5027.445,4979.005,5017.478,4 294 967 295,18.12 11:30
7,NaN,D&J-Ind*,30185.2,-0.41%,30320.440,30349.770,30035.560,30309.540,NaN,19.12 01:17
8,NaN,Futsee-100*,6529.18,-0.33%,6551.060,6604.540,6518.250,6551.060,NaN,18.12 19:35
9,NaN,Hang Seng (Гонконг),26414.15,-0.99%,26650.490,26668.100,26363.050,26678.380,NaN,18.12 10:59
10,NaN,KOSPI (Корея),2772.18,0.06%,2770.950,2782.150,2762.800,2770.430,1 046 824,18.12 09:32
11,NaN,Merval (Аргентина),52346.77,-1.45%,53115.580,53610.270,52200.920,53115.580,NaN,18.12 23:20
12,NaN,MICEX LC,2264.3 ₽,1.89%,2222.370,NaN,NaN,2222.360,21 850 894 535,17.05.13 18:44
13,NaN,MICEX MC,2059.02 ₽,2.55%,2007.730,NaN,NaN,2007.860,3 250 535 185,17.05.13 18:44
14,NaN,MICEXCBIGP,94.87 ₽,0.07%,94.820,NaN,NaN,94.800,3 364 431 230,24.12.13 18:32
15,NaN,MICEXCBIGP3Y,94.54 ₽,0.07%,94.490,NaN,NaN,94.470,2 015 644 343,24.12.13 18:18
16,NaN,MICEXCBIGP5Y,112.6 ₽,0.07%,112.520,NaN,NaN,112.520,1 112 133 869,24.12.13 18:32
17,NaN,MICEXMBIGP,97.88 ₽,0.05%,97.830,NaN,NaN,97.830,1 565 270 792,24.12.13 17:38
18,NaN,MOEXREPO акц 12:30,4.3 ₽,-0.23%,4.300,NaN,NaN,4.310,35 473 627 708,18.12 12:30
19,NaN,MOEXREPO акц 19:00,4.21 ₽,0%,0.000,NaN,NaN,4.210,NaN,05.11 00:00
20,NaN,MOEXREPO обл 12:30,4.29 ₽,-1.61%,4.290,NaN,NaN,4.360,267 068 473 338,18.12 12:30
21,NaN,MOEXREPO обл 19:00,4.21 ₽,0%,0.000,NaN,NaN,4.210,NaN,05.11 00:00
22,NaN,MOEXREPO1W обл 12:30,4.32 ₽,-0.92%,4.320,NaN,NaN,4.360,37 398 496 329,18.12 12:30
23,NaN,MOEXREPO1W обл 19:00,4.35 ₽,0%,0.000,NaN,NaN,4.350,NaN,05.11 00:00
24,NaN,MOEXREPOUSD обл 12:30,0.23 ₽,-4.17%,0.230,NaN,NaN,0.240,1 420 338 792,18.12 12:30
25,NaN,MOEXREPOUSD обл 19:00,0.5 ₽,0%,0.000,NaN,NaN,0.500,NaN,05.11 00:00
26,NaN,N225Jap*,26764.29,-0.16%,26775.530,26824.290,26707.300,26806.670,NaN,18.12 08:59
27,NaN,NASDAQ 100**,12738.18,-0.11%,12786.920,12793.470,12611.220,12752.060,NaN,19.12 00:00
28,NaN,NASDAQ**,12755.64,-0.07%,12804.930,12809.600,12654.600,12764.750,NaN,19.12 00:00
29,NaN,RCBI,99.59 ₽,-0.05%,99.680,NaN,NaN,99.640,258 652 338,21.04.08 17:40